version: '3.8'

services:
  node-app-prod:
    build:
      context: .
      target: production
    image: multi-tenant-poc-backend-prod
    env_file:
      - .env.production
    ports:
      - '3000:3000'