version: '3.8'

services:
  node-app:
    build:
      context: .
      target: development  # Specify the build target (development stage)
    image: multi-tenant-poc-backend
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/node-app
    # networks:
    #   - node-network

  # postgresdb:
  #   image: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=secret
  #   ports:
  #     - '5432:5432'
  #   volumes: 
  #     - dbdata:/var/lib/postgresql/data
  #   networks:
  #     - node-network

# volumes:
#   dbdata:
#     driver: local

# networks:
#   node-network:
#     driver: bridge
